---
include:
  # left
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # right
  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # dongle
  - board: nice_nano_v2
    shield: dongle
  # reset
  - board: nice_nano_v2
    shield: settings_reset
